### PR TITLE
Resolves #3

### LINKED ISSUE #3: Employee Filter
STORY
--------
I want to search all employees by employee id, name, position and department
so that I can filter all employees in the list

ACCEPTANCE CRITERIA
------------------------
GIVEN i have an employee id <1565>
WHEN I enter an employee id to the field
AND I press the search button
THEN I must see the employee in the list that has that employee id

### PR DESCRIPTION
**Pull request by Ccode0407**

### CODE REVIEW

**Review by eunizorozco — APPROVED** [review]
Nice.

**Review by sagitaryux — APPROVED** [review]
good game well played sir

**Comment by yintvrtle** [comment]
This is noice!

**Comment by LeandroAmores** [comment]
goodjob

**Pull request merged**
