### PR TITLE
Frontend/employees filter

### PR DESCRIPTION
**Pull request by sagitaryux**
please check and review my codes thanks!

### CODE REVIEW

**Review by eunizorozco — APPROVED** [review]

**Review by Ccode0407 — COMMENTED** [review]
GIT GUD SON

**Comment by yintvrtle** [comment]
Bitch your program sucks

**Comment by sagitaryux** [comment]
please check again thank you!

**Review by vergarabcs — APPROVED** [review]
hahaha

**Comment by sagitaryux** [comment]
@Ccode0407 @kasclem @eunizorozco @paulchristianprieto please check again thank you!

**Review by Ccode0407 — APPROVED** [review]

**Comment by yintvrtle** [comment]
This is noice

**Pull request merged**
